1-structure_de_groupe:
  title: "Structure de groupe"
  exercices: 33

2-classes_modulo_un_sous_groupe:
  title: "Classes modulo un sous-groupe"
  exercices: 10

3-groupes_monogenes:
  title: "Groupes monogènes, symétriques et diédraux"
  exercices: 33
      
4-sous_groupes_normaux:
  title: "Sous-groupes normaux"
  exercices: 38

5-groupe_operant_sur_un_ensemble:
  title: "Groupe opérant sur un ensemble"
  exercices: 27

6-groupes_finis:
  title: "Groupes finis. Théorèmes de Sylow"
  exercices: 26

7-suites_de_composition:
  title: "Suites de composition"
  exercices: 35
 
8-groupes_abeliens:
  title: "Groupes abéliens"
  exercices: 23

9-groupes_libres:
  title: "Groupes libres. Générateurs et relations. Produit libre de groupes"
  exercices: 12

